scene_path: '/data/zhongzd/git-project/Scalable-Neural-Indoor-Scene-Rendering/Datasets/data_snisr/renderData.npz'
cnn_path: '/data/zhongzd/git-project/Scalable-Neural-Indoor-Scene-Rendering/Datasets/data_snisr/cnn.pth'
# scene_path: '/home/yons/8TB/data/coffee/renderData.npz'
# cnn_path: '/home/yons/8TB/data/coffee/logs_unet/2022-01-25-17-50/epoch-230.pth'
height: 720
width: 1280
focal: 750
max_tracing_tile: 30
reflection_scale: 2
origin: [0,10,0]
tensorRT: True 